# Generated by Django 4.2.5 on 2024-02-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ulr',
            new_name='url',
        ),
    ]
